### ISSUE TITLE
Document Stele Linux setup

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/stele#10]
On Ubuntu you need to run:
```
apt-get install libgconf-2-4
```
before you'll be able to install or build the system.

This is a [known Electron issue](https://github.com/electron/electron/issues/1518), although it's not documented.

**Comment by bryankennedy** [comment]
Possibly clarify Linux install process. Recommend `.zip` over `.appimage`

**Comment by eojreyem** [comment]
@sanine-a and @brandonwkipp. Consider tackling this issue while installing on Raspberry Pi. Not sure if Rasp Pi compatibility/limitations warrant a separate ticket?

**Comment by bryankennedy** [comment]
Moved to Jira - https://smm.atlassian.net/browse/EXTCH-48
