### ISSUE TITLE
As a developer I want to reload the render process if a specific message appears in the render console.log() so that I can clear app errors outside of Stele

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/stele#34]

**Comment by bryankennedy** [comment]
@tnordberg we want this feature for the https://github.com/scimusmn/multiplayer-phone-game.

Do you have a specific string that you know would get thrown if the websockets issue appears? Here's what I'm imagining. I'd make a setting field that allowed you to enter a string. Then we'd watch the render process console.log() and if that string appeared, I'd ask the main process to reload the main window. Does that scratch your itch?

**Comment by azuldev1** [comment]
I agree. I think we should be careful of over bloating the application with overly specific features.

**Comment by bryankennedy** [comment]
On Slack today @tnordberg talked about a pressing need for this on the [multiplayer-phone-game](https://github.com/scimusmn/multiplayer-phone-game)

Moving it up in the schedule.

**Comment by tnordberg** [comment]
Would be great if the form should include a text-input for the string you're watching for, and four radio buttons:
• Disabled
• Contains 
• Starts with
• Ends with

**Comment by azuldev1** [comment]
kioskSettings object
{
messageReload:{message: "error 404", option:"disabled"}
}

**Comment by tnordberg** [comment]
This was finished, but has not been merged into master. It does what we described, with the exception of catching DOM generated errors. It only catches JS generated errors and logs.

**Comment by bryankennedy** [comment]
@tnordberg this has been merged now right? Can we close?

**Comment by tnordberg** [comment]
This has not been merged, and isn't being used in infestation. There was some discussion about whether we want it in the core of Stele, but we never decided.

**Comment by bryankennedy** [comment]
Sounds good. I'm moving this back to the backlog for now, since we need more thought about how to integrate this.

**Comment by bryankennedy** [comment]
Moved to Jira - https://smm.atlassian.net/browse/EXTCH-52
