### ISSUE TITLE
Production build drops down top menu bar when cursor hovers.

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/stele#45]
Issue seen on:
Mac Mini running:
OS X Yosemite 10.10.5

**Comment by bryankennedy** [comment]
@tnordberg mentioned that

> the menu bar dropdown only seems to happen when the app launches as a login-item, when I launch manually that behavior isn't there.

**Comment by bryankennedy** [comment]
This might be related to how macOS let's you launch a kiosk fullscreen window. We might need to do some more handling on startup to delay fullscreen mode until the system is fully up. We'll have to do some more testing. Is this a priority right now for the Illumination display? In this case the user can't activate the menu bar, right?

**Comment by tnordberg** [comment]
That's correct. This isn't an issue for illumination.

**Comment by bryankennedy** [comment]
This is Yosemite specific:
https://github.com/electron/electron/issues/1054

Electron marked this issue as won't fix, and I'll do the same. Yosemite is far enough back that we probably shouldn't worry about it for development. We can upgrade the OS on the Illumination display if we need to fix it there.

**Comment by bryankennedy** [comment]
I should add that it's working correctly on newer versions of macOS.
