### ISSUE TITLE
Evaluate upgrading Electron to v4

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/stele#47]

**Comment by azuldev1** [comment]
https://electronjs.org/releases/stable

**Comment by azuldev1** [comment]
some notable changes between version 3 and 4. 
Release Notes for v4.0.0
Breaking Changes
Upgraded to Chromium 69.0.3497.106 and Node 10.11.0. #13756, #14964, #14972
Changed to the new single instance API. #12782, #14518
Bumped minimum supported macOS version to 10.10. #15357

**Comment by bryankennedy** [comment]
Upgraded to address #82
