### ISSUE TITLE
Hide cursor feature should only be active on remote pages, not delay or setting pages

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/stele#52]
If you have the hide cursor setting enabled, it prevents you from using the Settings and Delay pages easily. The cursor should only be hidden when you're browsing the configured kiosk page.

**Comment by azuldev1** [comment]
someone already seems have resolved this issue:
`  // Ensure we are on our target kiosk URL
    if (currentURL.indexOf(reactHome) === -1)`
