### ISSUE TITLE
Stele crashes after running multiple days

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/stele#55]
Terminal output:

Stele(310,0x7fff771e1300) malloc: *** error for object 0x7fac4d07eb58: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

**Comment by tnordberg** [comment]
Looks like this has happened twice, with different error outputs...

Photo taken by Gail during Illumination:
![trygvegame_error](https://user-images.githubusercontent.com/8516314/51135284-3b452f80-17ff-11e9-8d0f-6f284e0e074c.JPG)

Screenshot taken after MacMini was left on for multiple days:
![screen shot 2019-01-14 at 1 08 09 pm](https://user-images.githubusercontent.com/8516314/51135295-413b1080-17ff-11e9-8783-4ffbc5f58454.png)

**Comment by tnordberg** [comment]
It is hinted here that updating Electron could fix the problem, but without supporting reasoning:

https://github.com/electron/electron/issues/10813

**Comment by bryankennedy** [comment]
Moved to Jira - https://smm.atlassian.net/browse/EXTCH-63
