### ISSUE TITLE
Don't require a display to be shown on the primary display

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/stele#72]
Right now, the system requires at least one display. This is currently linked to the primary display. There are some situations where it is likely that you might want Stele to appear on a secondary display, but not the primary one.

There's one thing we need to decide here. Should we require at least one display at all. This would actually be the simplest change to the code. This would allow you to configure Stele to run, but not show any windows. Otherwise we should just implement a requirement to have at least one display, and just let the configuring user set this to any display, not just the primary one.

Thoughts @tnordberg ?

**Comment by tnordberg** [comment]
Hmmm, I could imagine a _rare_ situation where we are using Stele to communicate with USB/Serial peripherals in an installed component, with no display. 

The question would then be how do we access the Settings if there is no display?

One idea is allowing configuring zero displays, then when you save, the settings window "Hides", with `Command + ,` popping it back up. 

If simpler, the Settings windows could stay open as a free-floating window, displaying a default Stele screen that says "Press `Command + ,` to access Settings".

**Comment by bryankennedy** [comment]
For now I'm keeping the main use case in mind for the latest design. You now can enable any display and aren't required to display anything on the primary display. But if nothing is enabled, then it will open the settings page automatically for you.

I think that there are more situations where we're going to be happy that the settings page automatically appears when nothing is configured in the app, than situations where we'd use this tool for no displays. We can revisit this as the need arises.
