### ISSUE TITLE
As a media developer, I want the ability to pass real-time data between multiple Windows, so multi screen components can react to each-other.

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/stele#81]
This can usually be handled through web sockets, but that requires an external server. There may be scenarios where it's simplest to only communicate locally through the Electron wrapper.
Let's think through this, because it might be a bad idea to rely on Stele here.

**Comment by bryankennedy** [comment]
I'm going to close this for now. I think this isn't something that we want to bake into Stele right now. This is really the responsibility of the app via react state or communication with the DB. If we ever have a need to handle this at the Electron level I think we should break that application out into its own Electron app.
