### ISSUE TITLE
Unable to build serial-comm branch for production. 

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/stele#82]
Running `yarn start` throws this error:
```
Uncaught Exception:
TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (/Users/tnordberg/Documents/SMM/Dev/stele/src/main/main.prod.js:1:64531)
```

**Comment by bryankennedy** [comment]
Do you have more context for this? Was the start command working at some point along the serial development branch?

**Comment by bryankennedy** [comment]
I believe that this is fixed now in the trunk. @tnordberg could you take a look?

**Comment by bryankennedy** [comment]
@tnordberg reported on Slack:

> Wahoo! I can package and run the mac .app with no issues on my Macbook.
> I’ll test the serial-communication first thing tomorrow morning.

If that all works, we can close this.

**Comment by bryankennedy** [comment]
This work is building correctly now and Trygve confirms that it is handling the serial communication correctly.
