### ISSUE TITLE
Stele silently crashes when starting up with a bad URL

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/stele#85]
For example, if you're pointing at a local server `http://localhost:3000/` in Settings, the launch Stele after stopping your server, Stele will crash without throwing an error.

**Comment by brandonwkipp** [comment]
I'm running into this issue right now, and it would be really nice if someone who knew more about it could document where Stele stores its settings; even after I delete the repo and reclone, the settings are still somehow preserved.

**Comment by calym** [comment]
Should probably reset if you delete the config.json here: library>application support>electron

**Comment by calym** [comment]
Or for a really thorough scrub: rm -rf ~/Library/Application\ Support/stele; rm -rf ~/Library/Application\ Support/Electron; rm -rf dll; rm -rf node_modules; rm -rf yarn.lock; yarn; say done; yarn start;

**Comment by bryankennedy** [comment]
Moved to Jira - https://smm.atlassian.net/browse/EXTCH-56
